### ISSUE TITLE
Feature request: navbar block

### ISSUE THREAD

**Issue by Webkadabra** [luyadev/luya-bootstrap3#13]

**Comment by nadar** [comment]
I don't think the nav bar should be part of the block. Navbar's are usually used within layout or cmslayout. So maybe create your own extension with the nav bar block, maybe some others are happy to. 

This repo is mainly thought to have content elements for "users working with content".

**Comment by Webkadabra** [comment]
@nadar what about `Tabs` block? I'm using `Navbar` (with affix plugin) to basically do the same thing as `Tabs` plugin would do - split content into sections, e.g. "About", "How to Use" etc. If we could include other blocks into Navbar/Tabs items that's be awesome.

**Comment by nadar** [comment]
Don't you not think this should be something from the cms layout or a sub page navigation from children? Maybe tabs would be an option, yes. There could be a use case for this. But maybe instead of adding more blocks to this repo, create your own extension with this boostrap3 "widgets" so people can decide, if they want to have booth, or only the content blocks, or the layout elements (your are talking about). What do you think?

**Comment by Webkadabra** [comment]
@nadar good idea! Sub-nav might work well

**Comment by nadar** [comment]
Going to close this, as there is a bootstrap 3 widget navbar (https://www.yiiframework.com/extension/yiisoft/yii2-bootstrap/doc/api/2.1/yii-bootstrap-navbar) but it currently makes no sense to have this as block, as this should be part of the layout file.
