### ISSUE TITLE
Request: add api key to maps block

### ISSUE THREAD

**Issue by mjvanmiddelaar** [luyadev/luya-bootstrap3#16]
An api key is required to use google maps since June 2018. Please consider adding  a field for an api key in the maps block.

See: https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by nadar** [comment]
Good point! I read something about this already as well, but what makes me currious is the fact that you can always klick the embed button on google maps itself, which then won't have an api key as well. example:

```
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d21608.596224600726!2d8.05233044263745!3d47.390978716928714!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47903bec161c5e71%3A0xcf4b48fa97997f1f!2sAarau!5e0!3m2!1sde!2sch!4v1534062871061" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
```

And as we are not using the javascript sdk in order to render the map (https://github.com/luyadev/luya-bootstrap3/blob/master/src/views/blocks/MapBlock.php) maybe its not required?

**Comment by nadar** [comment]
@luyadev/core Inputs?

**Comment by mjvanmiddelaar** [comment]
See also: https://developers.google.com/maps/documentation/embed/start

**Comment by nadar** [comment]
So they property to implement would be `&key=...` as far as i can see?

**Comment by nadar** [comment]
I will also add this hint: https://developers.google.com/maps/documentation/embed/get-api-key

**Comment by nadar** [comment]
Although i thinks we are not using embed api which would be (https://developers.google.com/maps/documentation/embed/guide) `https://www.google.com/maps/embed/v1` we are using the url `https://maps.google.com/maps` - not sure its the same, i just wanted to point this out. But it's in any case a good idea to have the key option, also for future usage.
